name: windows-latest

on:
  workflow_dispatch:

jobs:
  python:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        python-version: [ "3.14", "3.14t"  ] 
        exclude:
          - os: ubuntu-latest
            python-version: "3.11"
          - os: macos-latest
            python-version: "3.11" 
    name: Python ${{ matrix.python-version }} (${{ matrix.os }})
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        # allow-prereleases: true  # 3.15
        cache: pip

    - name: "pip install"
      shell: bash
      run: |
        export PYMEM_MALLOC=""
        python -m pip install --verbose .

    - name: "Print fcecodec.__version__, help"
      shell: bash
      run: |
        echo "import fcecodec as fc; print(f'import fcecodec as fc; fc.__version__={fc.__version__}')" > _version.py; cat _version.py
        python -c "import subprocess; import sys; retcode = subprocess.call([ sys.executable, '_version.py' ]); print('Exit code', retcode); sys.exit(0)"
        python -c "import fcecodec as fc; help(fc)" 
    - name: "Install requirements"
      shell: bash
      timeout-minutes: 1
      run: |
        python -m pip install numpy
        python -m pip install pytest

    - name: "pytest"
      shell: bash
      run: |
        pytest -s -vv ./tests/test_smoketest.py
        pytest -s -vv ./tests/test_diff.py
        pytest -s -vv ./tests/test_scripts.py
        pytest -s -vv ./tests/blender/test_fixblender.py
